/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./components/AppShell.vue')['default']
    BadgeViewer: typeof import('./components/BadgeViewer.vue')['default']
    CheckInFab: typeof import('./components/CheckInFab.vue')['default']
    CheckInModal: typeof import('./components/CheckInModal.vue')['default']
    CompetitionCompletionViewer: typeof import('./components/CompetitionCompletionViewer.vue')['default']
    CompetitionForm: typeof import('./components/CompetitionForm.vue')['default']
    CompetitionList: typeof import('./components/CompetitionList.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    FillRateHelpDialog: typeof import('./components/FillRateHelpDialog.vue')['default']
    PwaInstallPrompt: typeof import('./components/PwaInstallPrompt.vue')['default']
    PwaUpdatePrompt: typeof import('./components/PwaUpdatePrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastNotice: typeof import('./components/ToastNotice.vue')['default']
  }
}
