/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'calendar': RouteRecordInfo<
      'calendar',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'not-found': RouteRecordInfo<
      'not-found',
      '/:pathMatch(.*)*',
      { pathMatch: ParamValue<true> },
      { pathMatch: ParamValue<false> },
      | never
    >,
    'card': RouteRecordInfo<
      'card',
      '/card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'check-in': RouteRecordInfo<
      'check-in',
      '/check-in/:date?',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'competitions': RouteRecordInfo<
      'competitions',
      '/competitions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'competition-detail': RouteRecordInfo<
      'competition-detail',
      '/competitions/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | 'competition-edit'
    >,
    'competition-edit': RouteRecordInfo<
      'competition-edit',
      '/competitions/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'competition-history': RouteRecordInfo<
      'competition-history',
      '/competitions/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'competition-join': RouteRecordInfo<
      'competition-join',
      '/competitions/join',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'competition-new': RouteRecordInfo<
      'competition-new',
      '/competitions/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'setting': RouteRecordInfo<
      'setting',
      '/setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'setting-account': RouteRecordInfo<
      'setting-account',
      '/setting/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'setting-guide': RouteRecordInfo<
      'setting-guide',
      '/setting/guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'welcome': RouteRecordInfo<
      'welcome',
      '/welcome',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'calendar'
      views:
        | never
    }
    'src/pages/[...pathMatch].vue': {
      routes:
        | 'not-found'
      views:
        | never
    }
    'src/pages/card/index.vue': {
      routes:
        | 'card'
      views:
        | never
    }
    'src/pages/check-in/index.vue': {
      routes:
        | 'check-in'
      views:
        | never
    }
    'src/pages/competitions/index.vue': {
      routes:
        | 'competitions'
      views:
        | never
    }
    'src/pages/competitions/[id].vue': {
      routes:
        | 'competition-detail'
        | 'competition-edit'
      views:
        | 'default'
    }
    'src/pages/competitions/[id]/edit.vue': {
      routes:
        | 'competition-edit'
      views:
        | never
    }
    'src/pages/competitions/history.vue': {
      routes:
        | 'competition-history'
      views:
        | never
    }
    'src/pages/competitions/join.vue': {
      routes:
        | 'competition-join'
      views:
        | never
    }
    'src/pages/competitions/new.vue': {
      routes:
        | 'competition-new'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'src/pages/setting/index.vue': {
      routes:
        | 'setting'
      views:
        | never
    }
    'src/pages/setting/account/index.vue': {
      routes:
        | 'setting-account'
      views:
        | never
    }
    'src/pages/setting/guide/index.vue': {
      routes:
        | 'setting-guide'
      views:
        | never
    }
    'src/pages/welcome/index.vue': {
      routes:
        | 'welcome'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
